SevColApp/Models/Bank/UserBankAccounts.cs
using System.Collections.Generic;

namespace SevColApp.Models
{
    public class UserBankAccounts
    {
        public User User { get; set; }
        public List<BankAccount> BankAccounts { get; set; }
    }
}

SevColApp/Models/Gamemaster/AccountPasswordChange.cs
using System.ComponentModel.DataAnnotations;

namespace SevColApp.Models
{
    public class AccountPasswordChange
    {
        [Required]
        public string LoginName { get; set; }
        [Required]
        public string BankAccountName { get; set; }
        [Required]
        public string NewPassword { get; set; }
        public string Error { get; set; }
    }
}

SevColApp/Models/Gamemaster/AddStocksInputOutput.cs
using System.Collections.Generic;

namespace SevColApp.Models
{
    public class AddStocksInputOutput
    {
        public List<Company> Companies { get; set; }
        public List<User> Users { get; set; }
        public UserCompanyStocks UserCompanyStocks { get; set; }
        public int NumberOfStocks { get; set; }
        public List<string> Errors { get; set; }
    }
}

SevColApp/Models/Gamemaster/AllUsers.cs
using System.Collections.Generic;

namespace SevColApp.Models
{
    public class AllUsers
    {
        public List<User> Users { get; set; }
    }
}

SevColApp/Models/Gamemaster/EditBankAccountResult.cs
using System.Collections.Generic;

namespace SevColApp.Models
{
    public class EditBankAccountResult
    {
        public string FromAccount { get; set; }
        public string ToAccount { get; set; }
        public long AmountChange { get; set; }
        public long NewAmount { get; set; }
        public List<string> Errors { get; set; }
    }
}

SevColApp/Models/Gamemaster/InputOutputAccountEdit.cs
using System.Collections.Generic;

namespace SevColApp.Models
{
    public class InputOutputAccountEdit
    {
        public List<string> Errors { get; set; }
        public int Amount { get; set; }        
        public bool WithTransfer { get; set; }
        public string AccountNumber { get; set; }
        public bool FromRandomSevColAccount { get; set; }
        public string ToAccountNumber { get; set; }
        public string Description { get; set; }
        public BankAccount Account { get; set; }
    }
}

SevColApp/Models/Gamemaster/UserPasswordChange.cs
using System.ComponentModel.DataAnnotations;

namespace SevColApp.Models
{
    public class UserPasswordChange
    {
        [Required]
        public string UserLoginName { get; set; }
        [Required]
        public string NewPassword { get; set; }
        public string Error { get; set; }
    }
}

SevColApp/Models/Gamemaster/UserWithExtraData.cs
namespace SevColApp.Models
{
    public class UserWithExtraData
    {
        public User User { get; set; }
        public long TotalWealth { get; set; }
        public long TotalNumberOfStocks { get; set; }
    }
}

SevColApp/Models/Shared/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SevColApp.Models
{ 
    public class User
    {
        public int Id { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(50)]
        public string LoginName { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public string Prefixes { get; set; }
        public byte[] PasswordHash { get; set; }

        [NotMapped]
        public string FullName => string.IsNullOrEmpty(Prefixes) ? $"{FirstName} {LastName}" : $"{FirstName} {Prefixes} {LastName}";
        [NotMapped]
        public string Password { get; set; }
        [NotMapped]
        public bool IsGameMaster { get; set; }
        [NotMapped]
        public List<string> Errors { get; set; }
        public string AllowanceStatus { get; set; }
    }
}

SevColApp/Models/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SevColApp.Models
{
    public class User
    {
        public int Id { get; set; }
        [Required]
        [MinLength(3)]
        [MaxLength(50)]
        public string LoginName { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public string Prefixes { get; set; }
        public byte[] PasswordHash { get; set; }

        [NotMapped]
        public string FullName => string.IsNullOrEmpty(Prefixes) ? $"{FirstName} {LastName}" : $"{FirstName} {Prefixes} {LastName}";
        [NotMapped]
        public string Password { get; set; }
        [NotMapped]
        public bool IsGameMaster { get; set; }
        [NotMapped]
        public List<string> Errors { get; set; }
    }
}

SevColApp/Controllers/GamemasterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SevColApp.Helpers;
using SevColApp.Models;
using SevColApp.Repositories;
using System.Collections.Generic;
using System.Linq;

namespace SevColApp.Controllers
{
    public class GamemasterController : Controller
    {
        private readonly ILogger<GamemasterController> _logger;
        private readonly IGamemasterRepository _repo;
        private readonly IStocksRepository _stocksRepo;
        private readonly CookieHelper _cookieHelper;

        public GamemasterController(ILogger<GamemasterController> logger, IGamemasterRepository repo, IStocksRepository stocksRepo, CookieHelper cookieHelper)
        {
            _logger = logger;
            _repo = repo;
            _stocksRepo = stocksRepo;
            _cookieHelper = cookieHelper;
        }

        public IActionResult Index()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        public IActionResult Users()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            //var answer = new AllUsers { Users = _repo.GetAllUsers() };
            var answer = _repo.GetAllUsersWithExtraData();

            return View(answer);
        }

        public IActionResult PayUser(string userLoginName)
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var answer = _repo.PayAllowanceForUser(userLoginName);

            return View("Users", answer);
        }

        public IActionResult AllowanceReset()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var answer = _repo.ResetAllowances();

            return View("Users", answer);
        }

        public IActionResult EnterUserName()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var input = new EnterUserInputOutput
            {
                AllUsersLoginNames = _repo.GetAllUsers().Select(user => user.LoginName).ToList()
            };

            return View(input);
        }

        public IActionResult UsersBankAccounts(string userLoginName)
        {
            return EnterUserName(new EnterUserInputOutput { UserLoginName = userLoginName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EnterUserName(EnterUserInputOutput output)
        {
            var answer = _repo.GetAllAccountsOfUser(output.UserLoginName);

            return View("UserBankAccounts", answer);
        }

        public IActionResult ChangeUserPassword()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeUserPassword(UserPasswordChange input)
        {
            if (!ModelState.IsValid)
            {
                RedirectToAction("Index");
            }

            var result = _repo.ChangeUserPassword(input);

            return View("UserPasswordChanged", result);
        }

        public IActionResult ChangeBankAccountPassword()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeBankAccountPassword(AccountPasswordChange input)
        {
            if (!ModelState.IsValid)
            {
                RedirectToAction("Index");
            }

            var result = _repo.ChangeBankAccountPassword(input);

            return View("BankAccountPasswordChanged", result);
        }

        public IActionResult EditBankAccount(string accountNumber)
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var account = _repo.GetAccountByAccountNumber(accountNumber);

            var inputOutput = new InputOutputAccountEdit { Account = account, Errors = new List<string>() };

            return View(inputOutput);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditBankAccount(InputOutputAccountEdit input)
        {
            var answer = _repo.EditBankAccount(input);

            return View("EditBankAccountResult", answer);
        }

        public IActionResult AddCompany()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCompany(Company company)
        {
            var answer = _repo.AddCompany(company.Name);

            return View("AddCompanyResult", answer);
        }

        public IActionResult AddStocksForUser()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var input = new AddStocksInputOutput
            {
                Companies = _stocksRepo.GetAllCompanies(),
                Users = _repo.GetAllUsers(),
                UserCompanyStocks = new UserCompanyStocks()
            };

            return View(input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddStocksForUser(AddStocksInputOutput output)
        {
            output.Errors = new List<string>();

            var user = _repo.GetUserByLoginName(output.UserCompanyStocks.User.LoginName);

            var company = _stocksRepo.GetCompanyByName(output.UserCompanyStocks.Company.Name);

            if (user == null) output.Errors.Add($"No user was found with the login name \"{output.UserCompanyStocks.User.LoginName}\"");

            if (company == null) output.Errors.Add($"No company was found with the name \"{output.UserCompanyStocks.Company.Name}\"");

            if (output.NumberOfStocks == 0) output.Errors.Add($"A zero stocks change is pointless.");

            if (output.Errors.Count == 0)
            {
                output.UserCompanyStocks.Company = company;
                output.UserCompanyStocks.User = user;

                output.UserCompanyStocks.companyId = company.Id;
                output.UserCompanyStocks.userId = user.Id;

                output = _repo.AddStocksForUser(output);
            }

            return View("AddStocksForUserResult", output);
        }

        public IActionResult ViewStocksForUser()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var input = new EnterUserInputOutput
            {
                AllUsersLoginNames = _repo.GetAllUsers().Select(u => u.LoginName).ToList()
            };

            return View(input);
        }

        public IActionResult ViewStocksForThisUser(string userLoginName)
        {
            return ViewStocksForUser(new EnterUserInputOutput { UserLoginName = userLoginName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ViewStocksForUser(EnterUserInputOutput output)
        {
            var answer = _repo.GetStocksForUserByLoginName(output.UserLoginName);

            return View("ViewStocksForUserResult",answer);
        }
    }
}

SevColApp/Views/Gamemaster/AddCompany.cshtml
@model SevColApp.Models.Company

@{
    ViewData["Title"] = "Add company";
}

<html>
<body class="gmpage">

    <form asp-action="AddCompany">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right"><label>Company name:</label></th>
                <td>
                    <input asp-for="Name" class="form-control col-6" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </td>
            </tr>
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" class="btn btn-dark" />
                </td>
            </tr>
        </table>
    </form>

</body>
</html>

SevColApp/Views/Gamemaster/AddCompanyResult.cshtml
@model SevColApp.Models.Company

@{
    ViewData["Title"] = "Result of add company";
}

<html>
<body class="gmpage">

    @if (Model.IsNew)
    {
        <h5>The company @Model.Name has been added and given the id @Model.Id.</h5>
    }
    @if (!Model.IsNew)
    {
        <h5>The company @Model.Name already existed.</h5>
    }

    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">Back to game master page</a>

</body>
</html>

SevColApp/Views/Gamemaster/AddStocksForUser.cshtml
@model SevColApp.Models.AddStocksInputOutput

@{
    ViewData["Title"] = "Add stocks for a user";
}

<html>
<body class="gmpage">

    <form asp-action="AddStocksForUser">

        <table class="table table-borderless ">

            <tr>
                <th>User:</th>
                <td class="input-group float-left form-input">
                    <select asp-for="UserCompanyStocks.User.LoginName" class="custom-select">
                        <option selected>Choose the user</option>
                        @foreach (var user in @Model.Users)
                        {
                            <option>@user.LoginName</option>
                        }
                    </select>
                </td>
            </tr>

            <tr>
                <th>Company:</th>
                <td class="input-group float-left form-input">
                    <select asp-for="UserCompanyStocks.Company.Name" class="custom-select">
                        <option selected>Choose the desired company</option>
                        @foreach (var company in @Model.Companies)
                        {
                            <option>@company.Name</option>
                        }
                    </select>
                </td>
            </tr>

            <tr>
                <th>Number of stocks added (or subtracted if negative):</th>
                <td>
                    <input asp-for="NumberOfStocks" class="form-control form-input float-left" />
                    <span asp-validation-for="NumberOfStocks" class="text-danger"></span>
                </td>
            </tr>

            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" value="Choose" class="btn btn-light" />
                </td>
            </tr>

        </table>

    </form>


</body>
</html>

SevColApp/Views/Gamemaster/AddStocksForUserResult.cshtml
@model SevColApp.Models.AddStocksInputOutput

@{
    ViewData["Title"] = "Add stocks for user results page";
}

<html>
<body class="gmpage">

    @if (Model.Errors.Count > 0)
    {
        foreach (var error in Model.Errors)
        {
            <h5 class="text-danger">@error</h5>
        }
    }

    @if (Model.Errors.Count == 0)
    {
        <h5>Succesfully changed the number of stocks for @Model.UserCompanyStocks.User.LoginName.</h5>
        <h5>@Model.UserCompanyStocks.User.LoginName now has @Model.NumberOfStocks stocks for @Model.UserCompanyStocks.Company.Name.</h5>
    }

    <a asp-area="" asp-controller="Gamemaster" asp-action="AddStocksForUser" class="btn btn-outline-dark">Add stocks for a user again</a>

    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">Back to game master page</a>

</body>
</html>

SevColApp/Views/Gamemaster/BankAccountPasswordChanged.cshtml
@model SevColApp.Models.AccountPasswordChange

@{
    ViewData["Title"] = "User password changed";
}

<html>
<body class="gmpage">
    @if (string.IsNullOrEmpty(Model.Error))
    {
        <h2>The password of user's @Model.LoginName bank account "@Model.BankAccountName" has been changed to "@Model.NewPassword".</h2>
    }
    @if (!string.IsNullOrEmpty(Model.Error))
    {
        <h2>An error occurred:</h2>
        <h2>@Model.Error</h2>
    }

    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">Back to game master page</a>

</body>
</html>

SevColApp/Views/Gamemaster/ChangeBankAccountPassword.cshtml
@model SevColApp.Models.AccountPasswordChange

@{
    ViewData["Title"] = "Change user password";
}

<html>
<body class="gmpage">
    <form asp-action="ChangeBankAccountPassword">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right"><label>User's login name:</label></th>
                <td>
                    <input asp-for="LoginName" class="form-control col-6" />
                    <span asp-validation-for="LoginName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right"><label>Account name:</label></th>
                <td>
                    <input asp-for="BankAccountName" class="form-control col-6" />
                    <span asp-validation-for="BankAccountName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right"><label>Desired new password for the bank account:</label></th>
                <td>
                    <input asp-for="NewPassword" class="form-control col-6" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </td>
            </tr>
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" class="btn btn-dark" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

SevColApp/Views/Gamemaster/ChangeUserPassword.cshtml
@model SevColApp.Models.UserPasswordChange

@{
    ViewData["Title"] = "Change user password";
}

<html>
<body class="gmpage">
    <form asp-action="ChangeUserPassword">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right"><label>User's login name:</label></th>
                <td>
                    <input asp-for="UserLoginName" class="form-control col-6" />
                    <span asp-validation-for="UserLoginName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right"><label>User's desired new password:</label></th>
                <td>
                    <input asp-for="NewPassword" class="form-control col-6" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </td>
            </tr>            
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" class="btn btn-dark" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

SevColApp/Views/Gamemaster/EditBankAccount.cshtml
@model SevColApp.Models.InputOutputAccountEdit

@{
    ViewData["Title"] = "Edit bank account credits";
}

<html>
<body class="gmpage">
    @if (Model.Errors.Count == 0)
    {

    <form asp-action="EditBankAccount">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right"><label>Current credits:</label></th>
                <td>@Model.Account.Credit.ToString("N0")</td>
            </tr>
            <tr>
                <th class="text-right"><label>Amount in credits to add:</label></th>
                <td>
                    <input asp-for="Amount" class="form-control col-6" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </td>
            </tr>

            <tr>
                <th class="text-right"><label>Description (ignored if below 2 are empty):</label></th>
                <td>
                    <input asp-for="Description" class="form-control col-6" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </td>
            </tr>

            <tr>
                <th class="text-right"><label>With a transfer from random SevCol account:</label></th>
                <td>
                    <input asp-for="FromRandomSevColAccount" class="form-control col-6" />
                    <span asp-validation-for="FromRandomSevColAccount" class="text-danger"></span>
                </td>
            </tr>

            <tr>
                <th class="text-right"><label>With a transfer from account number:</label></th>
                <td>
                    <input asp-for="AccountNumber" class="form-control col-6" />
                    <span asp-validation-for="AccountNumber" class="text-danger"></span>
                </td>
            </tr>

            <tr>
                <td>
                    <input asp-for="ToAccountNumber" class="hide" type="hidden" value=@Model.Account.AccountNumber>
                </td>
            </tr>
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" class="btn btn-dark" />
                </td>
            </tr>
        </table>
    </form>
    }

    @if (Model.Errors.Count > 0)
    {
        @foreach(var error in Model.Errors)
            {
                <h4>@error</h4>
            }
    }
</body>
</html>

SevColApp/Views/Gamemaster/EditBankAccountResult.cshtml
@model SevColApp.Models.EditBankAccountResult

@{
    ViewData["Title"] = "Result from edit bank account credits";
}

<html>
<body class="gmpage">
    @if (Model.Errors.Count == 0)
    {
        <h4>Success! @Model.AmountChange.ToString("N0") credits have been transferred to @Model.ToAccount from @Model.FromAccount.</h4>
    }
    @if (Model.Errors.Count != 0)
    {
        <h4>Errors occurred:</h4>
        @foreach (var error in Model.Errors)
        {
            <h4>@error</h4>
        }
    }

    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">Back to game master page</a>

</body>
</html>

SevColApp/Views/Gamemaster/EnterUsername.cshtml
@model SevColApp.Models.EnterUserInputOutput
@{
    ViewData["Title"] = "Enter username to check all accounts of user";
}

<html>
<body class="gmpage">

    <form asp-action="EnterUserName">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">

            <tr>
                <th class="text-right"><label>User's login name:</label></th>
                <td class="input-group float-left form-input">
                    <select asp-for="UserLoginName" class="custom-select">
                        <option selected>Choose the user by login name:</option>
                        @foreach (var userLoginName in @Model.AllUsersLoginNames)
                        {
                            <option>@userLoginName</option>
                        }
                    </select>
                </td>
            </tr>

            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" class="btn btn-dark" />
                </td>
            </tr>

        </table>
    </form>
</body>
</html>

SevColApp/Views/Gamemaster/UserBankAccounts.cshtml
@model SevColApp.Models.UserAccountsAnswer

@{
    ViewData["Title"] = "All bank accounts of a user";
}

<html>
<body class="gmpage">
    <h3>These are the bank accounts beloning to "@Model.User.FullName".</h3>
    <table class="table table-borderless table-responsive">
        <thead>
            <tr>
                <th scope="col">Account id</th>
                <th scope="col">Account name</th>
                <th scope="col">Account number</th>
                <th scope="col">Credits</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.Accounts)
            {
                <tr>
                    <th scope="row">@account.Id</th>
                    <td>@account.AccountName</td>
                    <td>@account.AccountNumber</td>
                    <td>@account.Credit.ToString("N0")</td>
                    <td>
                        <a asp-area="" asp-controller="Gamemaster" asp-action="EditBankAccount" asp-route-accountNumber=@account.AccountNumber class="btn btn-outline-dark">Edit credit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">Back to game master page</a>

</body>
</html>

SevColApp/Views/Gamemaster/Users.cshtml
@model List<SevColApp.Models.UserWithExtraData>

@{
    ViewData["Title"] = "Gamemaster's all users page";
}

<html>
<body class="gmpage">
    <table class="table table-borderless table-responsive">
        <thead>
            <tr>
                <th scope="col">User id</th>
                <th scope="col">Login name</th>
                <th scope="col">Full name</th>
                <th scope="col">Total wealth</th>
                <th scope="col">Total stocks</th>
                <th scope="col">Allowance status</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <th scope="row">@user.User.Id</th>
                    <td>@user.User.LoginName</td>
                    <td>@user.User.FullName</td>
                    <td>@user.TotalWealth.ToString("N0")</td>
                    <td>@user.TotalNumberOfStocks.ToString("N0")</td>
                    <td class="text-success">@user.User.AllowanceStatus</td>
                    <td>
                        <a asp-area="" asp-controller="Gamemaster" asp-action="PayUser" asp-route-userLoginName=@user.User.LoginName class="btn btn-info">Pay allowance</a>
                        <a asp-area="" asp-controller="Gamemaster" asp-action="UsersBankAccounts" asp-route-userLoginName=@user.User.LoginName class="btn btn-info">Bank accounts</a>
                        <a asp-area="" asp-controller="Gamemaster" asp-action="ViewStocksForThisUser" asp-route-userLoginName=@user.User.LoginName class="btn btn-info">Stocks</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-area="" asp-controller="Gamemaster" asp-action="AllowanceReset" class="btn btn-info">Reset allowance statusses</a>
    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-outline-dark">Back to game master page</a>

</body>
</html>

SevColApp/Views/Gamemaster/ViewStocksForUser.cshtml
@model SevColApp.Models.EnterUserInputOutput

@{
    ViewData["Title"] = "VSelect a user to see their stocks";
} 

<html>
<body class="gmpage">

    <form asp-action="ViewStocksForUser">
        <table class="table table-borderless ">

            <tr>
                <th>User:</th>
                <td class="input-group float-left form-input">
                    <select asp-for="UserLoginName" class="custom-select">
                        <option selected>Choose the user</option>
                        @foreach (var user in @Model.AllUsersLoginNames)
                        {
                            <option>@user</option>
                        }
                    </select>
                </td>
            </tr>

            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" value="Choose" class="btn btn-light" />
                </td>
            </tr>

        </table>
    </form>



</body>
</html>

SevColApp/Views/Gamemaster/ViewStocksForUserResult.cshtml
@model List<SevColApp.Models.UserStocks>

@{
    ViewData["Title"] = "Add stocks for a user";
}

<html>
<body class="gmpage">

    <h4>This user currently has the following stocks:</h4>

    <ul>
        @foreach (var stocks in @Model)
        {
            <li>@stocks.Company.Name : @stocks.NumberofStocks stocks.</li>
        }
    </ul>

    <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">Back to game master page</a>

</body>
</html>