SevColApp/Controllers/BankController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SevColApp.Helpers;
using SevColApp.Models;
using SevColApp.Repositories;
using System.Collections.Generic;
using System.Linq;

namespace SevColApp.Controllers
{
    public class BankController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeRepository _userRepo;
        private readonly IBankRepository _repo;
        private readonly CookieHelper _cookieHelper;

        public BankController(ILogger<HomeController> logger, IHomeRepository userRepo, IBankRepository repo, CookieHelper cookieHelper)
        {
            _logger = logger;
            _userRepo = userRepo;
            _repo = repo;
            _cookieHelper = cookieHelper;

            _logger.LogInformation("Bank repository started");
        }

        public IActionResult Index()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var id = _cookieHelper.GetUserIdFromCookie();

            var viewInput = new UserBankAccounts
            {
                User = _userRepo.FindUserById(id),

                BankAccounts = _repo.GetBankAccountsOfUser(id)
            };

            return View(viewInput);
        }

        public IActionResult PasswordFill(int accountId)
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var account = _repo.GetBankAccountById(accountId);

            return View(account);
        }

        public IActionResult Details(BankAccount passwordData)
        {
            if (!ModelState.IsValid)
            {
                RedirectToAction("Privacy", "Home", null);
            }

            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var account = _repo.GetBankAccountById(passwordData.Id);

            var transfers = _repo.GetTransfersByAccountNumber(account.AccountNumber);

            var data = new BankAccountDetails() { Id = account.Id, AccountName = account.AccountName, AccountNumber = account.AccountNumber, Credit = account.Credit , Transfers = transfers};

            var passwordIsCorrect = _repo.IsAccountPasswordCorrect(account.AccountNumber, passwordData.Password);

            if (!passwordIsCorrect)
            {
                var answer = new InputAccountPasswordWrong
                {
                    AccountId = passwordData.Id
                };

                return View("PasswordCheck", answer);
            }            

            return View(data);
        }

        //public IActionResult Details(BankAccountDetails data)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return RedirectToAction("Privacy", "Home");
        //    }

        //    return View("Details", data);
        //}

        public IActionResult DetailsViaName(string accountName)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Privacy", "Home");
            }

            var data = _repo.GetBankAccountDetailsByAccountName(accountName);

            return View("Details", data);
        }

        public IActionResult Create()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var userId = _cookieHelper.GetUserIdFromCookie();

            var input = new InputOutputAccountCreate
            {
                UserHasAccount = (_repo.GetBankAccountsOfUser(userId)).Any(),

                Banks = _repo.GetAllBanks()
            };

            return View("Create", input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(InputOutputAccountCreate input) 
        {
            var possibleBankNames = _repo.GetAllBankNames();

            input = BankValidator.ValidateAccountInput(input, possibleBankNames);        

            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            if(input.Errors.Count == 0)
            {
                var userId = _cookieHelper.GetUserIdFromCookie();

                _repo.CreateNewAccount(input, userId);
            }            

            return View("AccountCreated",input);
        }

        public IActionResult Transfer(int accountId)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Privacy", "Home");
            }

            var data = new InputOutputTransfer
            {
                BankAccount = _repo.GetBankAccountById(accountId)
            };

            return View("Transfer", data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Transfer(InputOutputTransfer input)
        {
            var possibleAccounts = _repo.GetAllBankAccountNumbers();

            var transfer = BankValidator.ValidateTransfer(input.Transfer, possibleAccounts);

            if (transfer.Errors.Count == 0)
            {
                var passwordIsCorrect = _repo.IsAccountPasswordCorrect(input.Transfer.PayingAccountNumber, input.Password);

                if (passwordIsCorrect)
                {
                    transfer = _repo.ExecuteTransfer(transfer);
                }
                else
                {
                    transfer.Errors.Add("The account password was incorrect");
                }
                
            }

            return View("TransferResult", transfer);
        }
    }
}

SevColApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SevColApp.Helpers;
using SevColApp.Models;
using SevColApp.Repositories;
using System.Diagnostics;

namespace SevColApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeRepository _repo;
        private readonly CookieHelper _cookieHelper;

        public HomeController(ILogger<HomeController> logger, IHomeRepository repo, CookieHelper cookieHelper)
        {
            _logger = logger;
            _repo = repo;
            _cookieHelper = cookieHelper;
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Login()
        {
            if (_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("LoggedIn");
            }

            return View();
        }

        public IActionResult LoginUnknown()
        {
            return View();
        }

        public IActionResult LoggedIn()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login");
            }

            var id = _cookieHelper.GetUserIdFromCookie();

            var user = _repo.FindUserById(id);

            user.IsGameMaster = _cookieHelper.IsThereAGameMasterCookie();

            return View("LoggedIn", user);
        }

        public IActionResult Logout()
        {
            if (_cookieHelper.IsThereACookie())
            {
                _cookieHelper.RemoveCookie();
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User user)
        {
            if (string.IsNullOrEmpty(user.LoginName) || string.IsNullOrEmpty(user.Password))
            {
                return RedirectToAction("Privacy");
            }

            if (_repo.LoginIsCorrect(user))
            {
                var userId = _repo.FindUserIdByLoginName(user.LoginName);

                _cookieHelper.MakeACookie(userId);

                return RedirectToAction(nameof(LoggedIn));
            }

            //return BadRequest("Login name unknown or password is incorrect");
            return RedirectToAction(nameof(LoginUnknown));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(User user)
        {
            user = UserValidator.ValidateUser(user);

            if(user.Errors.Count == 0)
            {
                var userId = _repo.AddUserIfHeDoesNotExits(user);

                if (_repo.IsPasswordCorrect(user.Password, userId))
                {
                    _cookieHelper.MakeACookie(userId);
                }
                else
                {
                    user.Errors.Add("The password was incorrect.");
                }
            }

            return View("LoggedIn", user);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult DeleteUser()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login");
            }

            var id = _cookieHelper.GetUserIdFromCookie();

            _repo.DeleteUserById(id);

            _cookieHelper.RemoveCookie();

            return RedirectToAction("Login");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SevColApp/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SevColApp.Helpers;
using SevColApp.Models;
using SevColApp.Repositories;
using System.Linq;

namespace SevColApp.Controllers
{
    public class StocksController : Controller
    {
        private readonly IStocksRepository _repo;
        private readonly IHomeRepository _userRepo;
        private readonly IBankRepository _bankRepo;
        private readonly ILogger<StocksController> _logger;
        private readonly CookieHelper _cookieHelper;

        public StocksController(ILogger<StocksController> logger, IStocksRepository repo, IHomeRepository userRepo, IBankRepository bankRepo, CookieHelper cookieHelper)
        {
            _logger = logger;
            _repo = repo;
            _userRepo = userRepo;
            _bankRepo = bankRepo;
            _cookieHelper = cookieHelper;

            _logger.LogInformation("Stocks controller started");
        }

        public IActionResult Index()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var id = _cookieHelper.GetUserIdFromCookie();

            var userName = _userRepo.FindUserById(id).FullName;

            return View("Index", userName);
        }

        public IActionResult CurrentStocks()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var id = _cookieHelper.GetUserIdFromCookie();

            var usersStocks = _repo.GetStocksFromUser(id);

            return View(usersStocks);
        }

        public IActionResult BuyRequest()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var userId = _cookieHelper.GetUserIdFromCookie();

            var input = new BuyRequestInputOutput
            {
                Companies = _repo.GetAllCompanies(),
                BankAccounts = _repo.GetBankAccountsFromUser(userId),
                BuyRequest = new StockExchangeBuyRequest
                {
                    userId = userId
                }
            };

            return View("BuyRequest", input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult BuyRequest(BuyRequestInputOutput input)
        {
            StockExchangeBuyRequest answer;

            if(_bankRepo.IsAccountPasswordCorrect(input.BuyRequest.AccountNumber, input.BuyRequest.Password))
            {
                answer = _repo.AddBuyRequest(input.BuyRequest);
            }
            else
            {
                answer = input.BuyRequest;

                answer.Errors.Add($"The password for the account with account number {input.BuyRequest.AccountNumber} is incorrect or the account number is unknown.");
            }            

            return View("BuyRequestResults", answer);
        }

        public IActionResult SellRequest()
        {
            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var userId = _cookieHelper.GetUserIdFromCookie();

            var userStocks = _repo.GetStocksFromUser(userId);

            var input = new SellRequestInputOutput
            {
                UsersCurrentStocks = userStocks,
                BankAccounts = _repo.GetBankAccountsFromUser(userId),
                SellRequest = new StockExchangeSellRequest { userId = userId }
            };

            return View("SellRequest", input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SellRequest(SellRequestInputOutput request)
        {
            StockExchangeSellRequest answer;

            if (!_cookieHelper.IsThereACookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var userId = _cookieHelper.GetUserIdFromCookie();

            var possibleBankAccounts = _repo.GetBankAccountsFromUser(userId);

            if (possibleBankAccounts.Any(ba => ba.AccountNumber == request.SellRequest.AccountNumber))
            {
                answer = _repo.AddSellRequest(request.SellRequest);
            }
            else
            {
                answer = request.SellRequest;

                answer.Errors.Add($"The account number {request.SellRequest.AccountNumber} is not registered for this user or does not exist.");
            }            
            
            return View("BuyRequestResults", answer);
        }

        public IActionResult Test()
        {
            return View();
        }
    }
}

SevColApp/Views/Home/Create.cshtml
@model SevColApp.Models.User

@{
    ViewData["Title"] = "Home Page";
}

<html>
<body class="userpage">
    <form asp-action="create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right text-light"><label>Login name:</label></th>
                <td>
                    <input asp-for="LoginName" class="form-control col-6" />
                    <span asp-validation-for="LoginName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right text-light"><label>First name:</label></th>
                <td>
                    <input asp-for="FirstName" class="form-control col-6" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right text-light"><label>Last name:</label></th>
                <td>
                    <input asp-for="LastName" class="form-control col-6" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right text-light"><label>Prefixes (if any):</label></th>
                <td>
                    <input asp-for="Prefixes" class="form-control col-6" />
                    <span asp-validation-for="Prefixes" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right text-light"><label>Your password:</label></th>
                <td>
                    <input type="password" asp-for="Password" class="form-control col-6" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </td>
            </tr>
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" value="Create" class="btn btn-light" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

SevColApp/Views/Home/Index.cshtml
@model SevColApp.Models.User

@{
    ViewData["Title"] = "Home Page";
}

<html>

<body>
    <p>Please input your name:</p>


    <form asp-action="create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table>
            <tr>
                <th><label>First name:</label></th>
                <td>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th><label>Last name:</label></th>
                <td>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th><label>Prefixes (if any):</label></th>
                <td>
                    <input asp-for="Prefixes" class="form-control" />
                    <span asp-validation-for="Prefixes" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th><label>Your password:</label></th>     
                <td>
                    <input asp-for="Password" class="form-control"/>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </td>
            </tr>
            <tr class="form-group">
                <td>
                    <input type="submit" value="Create" class="btn btn-primary" />
                </td>
            </tr>
        </table>
    </form>
</body>


</html>

SevColApp/Views/Home/LoggedIn.cshtml
@model SevColApp.Models.User

@{
    ViewData["Title"] = "Home Page";
}

<html>
<body class="userpage">


    @if (Model.Errors.Count == 0)
    {
        <h1 class="col align-self-center text-light">Welcome, @Model.FullName.</h1>

        @if (Model.IsGameMaster)
        {
            <a asp-area="" asp-controller="Gamemaster" asp-action="Index" class="btn btn-info">GameMaster things</a>
        }

        <a asp-area="" asp-controller="Bank" asp-action="Index" class="btn btn-light">Banking</a>

        <a asp-area="" asp-controller="Stocks" asp-action="Index" class="btn btn-light">Stocks</a>

        <a asp-area="" asp-controller="Home" asp-action="Logout" class="btn btn-secondary">Logout</a>
    }
    @if (Model.Errors.Count > 0)
    {
        if (Model.Errors.Count > 1)
        {
            <h3 class="text-warning">@Model.Errors.Count errors occurred during logging in:</h3>
        }
        if (Model.Errors.Count == 1)
        {
            <h3 class="text-warning">An error occurred during logging in:</h3>
        }
        @foreach (var error in @Model.Errors)
        {
            <h4 class="text-warning">@error</h4>
        }

        <a asp-area="" asp-controller="Home" asp-action="Create" class="btn btn-light">Try again</a>
    }

</body>
</html>

SevColApp/Views/Home/Login.cshtml
@model SevColApp.Models.User

@{
    ViewData["Title"] = "Home Page";
}

<html>

<body class="userpage">
    <form asp-action="login">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right text-light"><label>Login name:</label></th>
                <td>
                    <input asp-for="LoginName" class="form-control col-6" />
                    <span asp-validation-for="LoginName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right text-light"><label>Your password:</label></th>
                <td>
                    <input type="password" asp-for="Password" class="form-control col-6" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </td>
            </tr>
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" value="Login" class="btn btn-light" />
                </td>
            </tr>
            <tr>
                <th></th>
                <td>
                    <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Create">Create new account</a>
                </td>
            </tr>
        </table>

    </form>
</body>


</html>

SevColApp/Views/Home/LoginUnknown.cshtml
@model SevColApp.Models.User

@{
    ViewData["Title"] = "Home Page";
}

<html>

<body class="userpage">
    <form asp-action="login">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table-borderless table-sm">
            <tr>
                <th class="text-right text-light"><label>Login name:</label></th>
                <td>
                    <input asp-for="LoginName" class="form-control col-6" />
                    <span asp-validation-for="LoginName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="text-right text-light"><label>Your password:</label></th>
                <td>
                    <input type="password" asp-for="Password" class="form-control col-6" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </td>
            </tr>
            <tr class="form-group">
                <th></th>
                <td>
                    <input type="submit" value="Login" class="btn btn-light" />
                </td>
            </tr>
            <tr>
                <th></th>
                <td>
                    <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Create">Create new account</a>
                </td>
            </tr>
            <tr>
                <th></th>
                <td class="text-danger">Login name unknown or password incorrect</td>
            </tr>
        </table>
    </form>
</body>


</html>

SevColApp/Views/Home/Logout.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html>
<body class="userpage">
    <h1 class="text-light">You have been logged out</h1>
    <a asp-area="" asp-controller="Home" asp-action="Login" class="btn btn-light">Home</a>
</body>
</html>