SevColApp/Controllers/GamemasterStockExchangeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SevColApp.Helpers;
using SevColApp.Models;
using SevColApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SevColApp.Controllers
{
    public class GamemasterStockExchangeController : Controller
    {
        private readonly ILogger<GamemasterController> _logger;
        private readonly IGamemasterStockExchangeRepository _repo;
        private readonly IStocksRepository _stocksRepo;
        private readonly CookieHelper _cookieHelper;

        public GamemasterStockExchangeController(ILogger<GamemasterController> logger, IGamemasterStockExchangeRepository repo, IStocksRepository stocksRepo, CookieHelper cookieHelper)
        {
            _logger = logger;
            _repo = repo;
            _stocksRepo = stocksRepo;
            _cookieHelper = cookieHelper;
        }

        public IActionResult Index()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        public IActionResult GlobalVariables()
        {
            if (!_cookieHelper.IsThereAGameMasterCookie())
            {
                return RedirectToAction("Login", "Home");
            }

            var input = new Global
            {
                Errors = new List<string>(),
                MarketTrendFactor = _repo.GetGlobalTrend(),
                MarketVolatility = _repo.GetGlobalVolatility()
            };

            return View(input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GlobalVariables(Global input)
        {
            input.Errors = new List<string>();

            var newMarketTrendValue = ChangeInputStringsToFloats(input.InputStringTrend);
            var newMarketVolatilityValue = ChangeInputStringsToFloats(input.InputStringVolatility);

            if(input.Errors.Count == 0)
            {
                _repo.SetGlobalTrend(newMarketTrendValue);
                _repo.SetGlobalVolatility(newMarketVolatilityValue);

                input.MarketTrendFactor = _repo.GetGlobalTrend();
                input.MarketVolatility = _repo.GetGlobalVolatility();
            }

            return View("GlobalVariables", input);

            float ChangeInputStringsToFloats(string inputString)
            {
                float output;
                bool parseable;

                var indexOfSeparator = inputString.IndexOf(".");

                if (indexOfSeparator == -1)
                {
                    indexOfSeparator = inputString.IndexOf(",");
                }

                if(indexOfSeparator == -1)
                {
                    parseable = float.TryParse(inputString, System.Globalization.NumberStyles.Float, null, out output);
                }
                else
                {
                    var localInputString = inputString.Substring(0, indexOfSeparator) + "," + inputString.Substring(indexOfSeparator+1);
                    parseable = float.TryParse(localInputString, System.Globalization.NumberStyles.Float, null, out output);
                }

                if (!parseable)
                {
                    input.Errors.Add($"The input value \"{ inputString}\" could not be parsed to a float.");
                    return 1;
                }
                else
                {
                    return output;
                }
            }
        }
    }
}

SevColApp/Views/GamemasterStockExchange/GlobalVariables.cshtml
@model SevColApp.Models.Global

@{
    ViewData["Title"] = "Change Global variables page";
}

<html>
<body class="gmpage">
    @if (Model.Errors.Count == 0)
    {
        <form asp-action="GlobalVariables">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <table class="table table-borderless table-sm">
                <tr>
                    <th>Current global trend multiplier:</th>
                    <td> @Model.MarketTrendFactor</td>
                </tr>
                <tr>
                    <th class="text-right"><label>New value:</label></th>
                    <td>
                        <input asp-for="InputStringTrend" class="form-control col-6" />
                        <span asp-validation-for="InputStringTrend" class="text-danger"></span>
                    </td>
                </tr>
                <tr></tr>
                <tr>
                    <th>Current global volatility:</th>
                    <td> @Model.MarketVolatility</td>
                </tr>
                <tr>
                    <th class="text-right"><label>New value:</label></th>
                    <td>
                        <input asp-for="InputStringVolatility" class="form-control col-6" />
                        <span asp-validation-for="InputStringVolatility" class="text-danger"></span>
                    </td>
                </tr>
                <tr class="form-group">
                    <th></th>
                    <td>
                        <input type="submit" class="btn btn-dark" />
                        <a asp-area="" asp-controller="GamemasterStockExchange" asp-action="Index" class="btn btn-dark">Done</a> <br />
                    </td>
                </tr>
            </table>
        </form>
    }
    @if (Model.Errors.Count > 0)
    {
        @foreach (var error in Model.Errors)
        {
            <h4>@error</h4>
        }
        <a asp-area="" asp-controller="GamemasterStockExchange" asp-action="GlobalVariables" class="btn btn-outline-dark">Try again</a> <br />
        <a asp-area="" asp-controller="GamemasterStockExchange" asp-action="Index" class="btn btn-outline-dark">Never mind</a> <br />
    }
</body>
</html>

SevColApp/Views/GamemasterStockExchange/Index.cshtml
@{
    ViewData["Title"] = "Gamemaster stock exchange page";
}

<html>
<body class="gmpage">
    <h1>Welcome to the game master's stock exchange page</h1>

    <a asp-area="" asp-controller="GamemasterStockExchange" asp-action="GlobalVariables" class="btn btn-outline-dark">Change the global stock exchange variables</a> <br />
</body>
</html>